"""initial_schema

Revision ID: 417e7440062a
Revises: 
Create Date: 2026-05-24 01:23:29.784903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '417e7440062a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('email_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_verifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_verifications_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_email_verifications_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mls_id', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('address_street', sa.String(), nullable=False),
    sa.Column('address_city', sa.String(), nullable=False),
    sa.Column('address_state', sa.String(), nullable=False),
    sa.Column('address_zip', sa.String(), nullable=False),
    sa.Column('property_type', sa.String(), nullable=False),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Integer(), nullable=True),
    sa.Column('garage', sa.String(), nullable=True),
    sa.Column('square_feet', sa.Integer(), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=11, scale=2), nullable=False),
    sa.Column('annual_interest_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('mortgage_term', sa.Integer(), nullable=False),
    sa.Column('down_payment', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('closing_costs', sa.Numeric(precision=11, scale=2), nullable=False),
    sa.Column('initial_repairs', sa.Numeric(precision=9, scale=2), nullable=True),
    sa.Column('pmi_monthly', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('rent_lower', sa.Numeric(precision=9, scale=2), nullable=False),
    sa.Column('rent_upper', sa.Numeric(precision=9, scale=2), nullable=False),
    sa.Column('property_tax_annual', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('property_tax_url', sa.String(), nullable=True),
    sa.Column('hoa_annual', sa.Numeric(precision=9, scale=2), nullable=True),
    sa.Column('property_management_annual', sa.Numeric(precision=9, scale=2), nullable=False),
    sa.Column('vacancy_days_annual', sa.Integer(), nullable=False),
    sa.Column('maintenance_annual', sa.Numeric(precision=9, scale=2), nullable=False),
    sa.Column('insurance_annual', sa.Numeric(precision=9, scale=2), nullable=False),
    sa.Column('rent_increase_pct', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('maintenance_increase_pct', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('appreciation_rate_pct', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('property_tax_increase_pct', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('insurance_increase_pct', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_properties_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_properties_id'))

    op.drop_table('properties')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('email_verifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_verifications_id'))
        batch_op.drop_index(batch_op.f('ix_email_verifications_email'))

    op.drop_table('email_verifications')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
