"""add_password_resets_table

Revision ID: 6f57df07451f
Revises: 417e7440062a
Create Date: 2026-05-27 21:59:34.840782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f57df07451f'
down_revision: Union[str, Sequence[str], None] = '417e7440062a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_resets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_resets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_resets_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_password_resets_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_resets_token'), ['token'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password_resets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_resets_token'))
        batch_op.drop_index(batch_op.f('ix_password_resets_id'))
        batch_op.drop_index(batch_op.f('ix_password_resets_email'))

    op.drop_table('password_resets')
    # ### end Alembic commands ###
